apiVersion: v1
kind: Service
metadata:
  labels:
    app: lykke-mailerlite-worker
    environment: Development
  name: lykke-mailerlite-worker
  namespace: lykke-exchange
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: lykke-mailerlite-worker
  sessionAffinity: None
  type: ClusterIP
