apiVersion: v1
kind: Service
metadata:
  labels:
    app: lykke-mailerlite
    environment: Development
  name: lykke-mailerlite
  namespace: lykke-exchange
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: lykke-mailerlite
  sessionAffinity: None
  type: ClusterIP
